version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ada@wongcom
      PGADMIN_DEFAULT_PASSWORD: dina123
    ports:
      - "5050:80"
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
